### ISSUE TITLE
Resolving a promise1 with a promise2 should return the promise2 resolved value

### ISSUE THREAD

**Issue by astik** [dracupid/light-promise#2]
Here is the code for the resolve function :

``` js
    Promise.prototype.resolve = function(value1) {
      this.value = value1;
      if (this.state === 'fulfilled') {
        return this;
      }
      this.state = 'fulfilled';
      this._fireResolve();
      return this;
    };
```

On https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve, documentation says :

```
The Promise.resolve(value) method returns a Promise object that is resolved with the given value. If the value is a thenable (i.e. has a then method), the returned promise will "follow" that thenable, adopting its eventual state; otherwise the returned promise will be fulfilled with the value.
```

So that, value1 should be resolved before getting affected to this.value.

As a workaround, till fixing the library, we can code this by resolving promise2 and then resolving promise1 :

instead of coding this :

``` js
   var promise1 = new Promise();
   var promise2 = new Promise();
   promise1.resolve(promise2);
```

we can code that :

``` js
   var promise1 = new Promise();
   var promise2 = new Promise();
   promise2.then(function(value){
      promise1.resolve(value);
   }
```

**Comment by dracupid** [comment]
That's it! 👍 This is exactly the reason why I failed to pass test case 2.3.3 of [promises-tests](https://github.com/promises-aplus/promises-tests). I have review my `resolveX` function and the source code of promises-tests many times but failed to figure out this bug. I just ignored this sample case. Thank you sooooooo much!  😄 

TIPS: According to chrome v8's implementation of `Promise`, you cannot:
- new `Promise` object with no arguments
- call resolve on a promise object instead of `Promise` constructor, which is not a standard API

what you may want could be:

``` js
var promise2 = Promise.resolve()
var promise1 = Promise.resolve(promise2)
```

**Comment by astik** [comment]
FYI, my code example was more proto-code, than actual javascript code =P

Thanks for the fix !
